name: Java CI with Maven and Postgres Docker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Start Postgres DB Container
        run: docker compose up -d postgres-db

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B clean test
        env:
          TZ: Asia/Novosibirsk
          JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Novosibirsk
          SPRING_JACKSON_TIME_ZONE: Asia/Novosibirsk
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/shareit
          SPRING_DATASOURCE_USERNAME: postgres_user
          SPRING_DATASOURCE_PASSWORD: password

      - name: Stop and clean Containers
        if: always()
        run: docker compose down -v

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: maven-test-reports
          path: target/surefire-reports/